@SalesAnalytics.Api_HostAddress = http://localhost:5170

### Disparar proceso ETL (Staging -> ODS -> Data Warehouse)
POST {{SalesAnalytics.Api_HostAddress}}/api/etl/ejecutar
Accept: application/json

###

### Consultar resumen de registros en el Data Warehouse
GET {{SalesAnalytics.Api_HostAddress}}/api/dw/resumen
Accept: application/json

###
